language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: FUfsgPz5sdgslc9it4e2yzi0e4y7Uuuj2beyojAh0sn9n0MhRJm0odJ3pMjiXk+a2473iVz+roqEsqiGq/I3z7KaNaoYMiWj50ZxIiDbmMA4UmxToZqpu/M3kiswkr+ao3N8IhPPIOUTDtaScYtcTT9X07fTubpS+7jnnFLxJtnRGOfFtLvzgQ7ugC9Gt4RaE3BE2sE1adrYiqfN+76CKe4wYNTPvl9cKJ/CKjZFujWnnK67mpCORLFpMXu411lHRbN6QHfxmEKmD5fgI92pw/ANIwbbm9RHG+awFUk58fuTriLzJS3184LbGl5tOJwbKN1e5FOj1qxlmYBDHNYxANm0LeHQOarvvdEYZF/K4JPTt7d2UlavBpSOgythvIe01On3n2n3VBZ4Xm9qZ6EYT3t9q3IxspgNft/xMR0+mdFqgfPMS538ZMQvDQ5eV2qvaEsM77I81iwLIKanFVkzN/IR7aHK4reSLk0sQLBFmv0xphkzjaqOEjfbJ3Qsf6qDcgbd6+TWl6rLUR2K5hMTTCGDMkFvxUiJnDiaEMYJ0rdRt2U3DDRG0aO3wfKacRx6Rt9lV07xZPqrNlcO9ZnqpBiQMTAugpHEywT2Yv0KmItA6FzqO7RHg6e+5Hg2gTS9YANX+UV7k7D55Q4aG/6669JUTQjvCy45DuC9ype4DTA=
  app: builder-workout
  on:
    repo: b-chang93/builder
