language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: E1lposSoDf3YzT0XYBGMra8yjaMW1jKwh9IAEfGwSIjvT+djG24CJcKtObPUmMw5ofI9YztK5zSJV9p12zQY/YteYecNfrwvBFinPVA8QEQ8MDguD5AomJ4M0FRjKs6JkAuOhtuikJ6Qr0A6HjT0HxWQGWbJijqqspR9YbbXRCZ9F5fCgkVh4HOc3aXC2Ndfms2K6iAaGsUTGcBY7U/9UNYMU+As/J/kTGmISDno3KSq2ey8zFNNOr3AojmaDPXh0X0P+6giKeoiRqy5ajVez0ddNo8Bd14JXQwO9Y25XBRVJOGkvrfsSlHQKNowAP34bz5749cfkrALS99rbTOsLbpqS6hxblsEj6GSGYZtZ9gpG1yYYyS9COxMJoXdHTn5RyEf57Nhmzq67reOizL5Mwo9G6USrSWa09adhoUALojBIVFMWQz9tAmicCSte0zX64FEVzz7RmiC4ug7TTJMnQgaj2pXWcub8vqpwkjLvqcQyWqtxFn2vgmHdNN+5u3Nea12lbuaclP4TJ4rgh4U29Ad1VIktgMjodyf+irzYJYyTsFQoNQO9NgiwaX0H5xz95UMiqkpso5kBNymnCYhvUvlmrcXr6yCqCqF+ZDCWV4GM+8SuavqrG9dpP54udHm4xDXnYTB7vTdzkWwRiLOaXcPhOM8Kp+ia52CpTIDFDM=
  app: builder
  on:
    repo: b-chang93/builder
